MIGRATION_MSG?=autogenerated
REVISION?=head
DOWNGRADE_STEP?=-1

VENV=.venv
PIP=$(VENV)/bin/pip
PY=$(VENV)/bin/python
DC=docker compose

.DEFAULT_GOAL := help

help: ## Показать список целей и их описание
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*## "}; /^[a-zA-Z0-9_.-]+:.*## / {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

install: ## Установить зависимости локально и подготовить окружение
	test -d $(VENV) || python3 -m venv $(VENV)
	$(PIP) install --upgrade pip
	$(PIP) install -r requirements.txt
	mkdir -p data src/alembic/versions
	$(MAKE) build

build: ## Собрать Docker образы
	$(DC) build

api: ## Запустить только сервис API
	$(DC) up -d --build api

consumer: ## Запустить только сервис Consumer
	$(DC) up -d --build consumer

run: ## Запустить все сервисы (PostgreSQL, RabbitMQ, API, Consumer)
	$(DC) up -d --build

down: ## Остановить все сервисы
	$(DC) down

revision: ## Создать новую миграцию Alembic (использовать MIGRATION_MSG="...")
	$(DC) exec api alembic revision --autogenerate -m "$(MIGRATION_MSG)"

migrate: ## Применить миграции до указанной ревизии (по умолчанию head)
	$(DC) exec api alembic upgrade $(REVISION)

downgrade: ## Откатить миграции на указанный шаг (по умолчанию -1)
	$(DC) exec api alembic downgrade $(DOWNGRADE_STEP)

logs: ## Показать логи API и Consumer
	$(DC) logs -f api consumer

clean: ## Остановить сервисы и удалить volumes (очистить БД и RabbitMQ)
	$(DC) down --volumes --remove-orphans

test: ## Запустить тесты
	$(PY) -m pytest tests/

.PHONY: \
	help install build api consumer run down \
	revision migrate downgrade \
	logs clean test
